#!/usr/bin/env python3

import sys
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd

df = pd.read_json(sys.argv[1])

li = pd.DataFrame.from_records(df['bill']['line_items'])

# remove negative numbers @TODO should be a filter for "type": "payment"
li = li[(li[["amount"]] > 0).all(1)]

# from cents to reais
li["amount_brl"] = li["amount"].apply(lambda x: x / 100)

print(li.head())

sns.catplot(x="category",
            y="amount_brl",
            data=li,
            kind="box",
            ci=None
            )
plt.show()
